name: 'Build Artifact Uploader'
description: 'Zips and uploads the build artifact to S3'
author: "Anil Raj Rimal" 
inputs:
  aws-access-key-id:
    required: true
    description: 'AWS access key ID'
  aws-secret-access-key:
    required: true
    description: 'AWS secret access key'
  aws-region:
    required: true
    default: 'ap-south-1'
    description: 'AWS region'
  project-name:
    required: true
    description: 'Name of the project'
  s3-base-path:
    required: true
    description: 'Base S3 path for uploads'
  source-directory:
    required: false
    default: 'dist'
    description: 'Directory to zip and upload'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Zip contents and upload to S3
      shell: bash
      run: |
        set -e

        PROJECT_NAME="${{ inputs.project-name }}"
        RUN_ID="${{ inputs.run-id }}"
        RUN_NUMBER="${{ inputs.run-number }}"
        SOURCE_DIRECTORY="${{ inputs.source-directory }}"
        S3_BASE_PATH="${{ inputs.s3-base-path }}"

        ZIP_NAME="${PROJECT_NAME}-${RUN_ID}-${RUN_NUMBER}.zip"
        ABS_SOURCE_DIR="$(realpath "$SOURCE_DIRECTORY")"
        PARENT_DIR="$(dirname "$ABS_SOURCE_DIR")"
        ZIP_PATH="${PARENT_DIR}/${ZIP_NAME}"
        S3_BUILD_PATH="${S3_BASE_PATH}/${PROJECT_NAME}-${RUN_ID}/${ZIP_NAME}"

        cd "$ABS_SOURCE_DIR"
        zip -r "$ZIP_PATH" . > /dev/null
        cd - > /dev/null

        aws s3 cp "$ZIP_PATH" "$S3_BUILD_PATH"

        echo "✅ Upload complete: $S3_BUILD_PATH"

        rm "$ZIP_PATH"

branding:
    icon: "arrow-up"
    color: "green" 